name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - deploy-frontend # Điền chính xác tên branch bạn đang code và chuẩn bị push lên

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cài đặt thư viện và Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Đẩy gói build lên nhánh gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist # Thư mục sinh ra sau khi build của Vite
          branch: gh-pages # Tên nhánh chứa code chạy trực tuyến